name = "primeos"
license = "MIT"
licenselink = "https://github.com/primeos/hugo-theme-primeos/blob/master/LICENSE.txt"
description = "A simple Hugo theme based on hello-friend-ng."
tags = ["personal", "blog", "minimal"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30
